### ISSUE TITLE
Keep info panel open

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#50]
Once the information panel is opened, it should stay open.

Steps:
- Visit a site
- Toggle the info panel
- click on a link
  The panel is closed and the user must reopen the panel.

**Comment by michaelsframe** [comment]
Agreed, this was first pass to prove functionality.  The panel has a few issues that need to be addressed:
- Panel should not be available on Datawake Depot pages (and trailing should not occur on Depot pages)
- Once opened the Panel should stay open on a given page
- Panel widgets are currently set to refresh every 5 seconds.  This continually re-draws the panel and can be annoying to the user.  Widgets should be set to initially load the data and have a "refresh" button on them so that the user can refresh when they want to.  Ultimately we'll need a way to show the user that new data is available.  Maybe we don't show the refresh button until there are new results to show?

**Comment by michaelsframe** [comment]
Had to handle some additional items in #21, but can mark this complete.

Panel not available in depot pages done in #53.  Panel also cannot be opened if you are not 1) logged in and 2) actively trailing.
Panel stays open on a given page unless the user toggles the panel off in the toolbar (#21), or if the user stops actively trailing.
Panel widget set to load once and now has a refresh button to request current data.  This could use some rework (currently waits 4 seconds to load, should really check until it has real data). #50
