### ISSUE TITLE
Info panel doesn't open on some sites

### ISSUE THREAD

**Issue by bwhiteman** [Sotera/DatawakeDepot#51]
The info panel does not open on some sits. Examples include: reuters.com, wsj.com

**Comment by michaelsframe** [comment]
Without some major rework with how the panel is inserted into a page this will not be easy to address.  At best we need to log which urls we have problems with so that we have good test data for improvements.

Maybe we should add a Toolbar button to "Tag troublesome webpage", so that we can at least log it to look at later?

**Comment by bwhiteman** [comment]
Closed as duplicate of #52
